name       : po4a
version    : 0.47
release    : 1
# Why the custom URL? Because alioth is a monumental and unfriendly PITFA.
source     :
    - https://solus-project.com/sources/po4a-0.47.tar.gz : 5010e1b7df1115cbd475f46587fc05fefc97301f9bba0c2f15106005ca017507
license    : GPL-2.0
summary    : po4anything
description: |
    po4anything
builddeps  :
    - docbook-xml
patterns   :
    - /usr/share/man
setup      : |
    perl Build.PL installdirs=vendor create_packlist=0
build      : |
    perl Build
install    : |
    perl Build destdir=${installdir} install
    rm -rf $installdir/usr/lib/perl5/5.20.1
