name       : po4a
version    : 0.47
release    : 3
source     :
    - https://solus-project.com/sources/po4a-0.47.tar.gz : 5010e1b7df1115cbd475f46587fc05fefc97301f9bba0c2f15106005ca017507
license    : GPL-2.0
summary    : po4anything
component  : programming.devel
description: |
    po4anything
builddeps  :
    - docbook-xml
    - perl-module-build
patterns   :
    - /usr/share/man
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
