name       : po4a
version    : 0.59.1
release    : 8
source     :
    - https://github.com/mquinson/po4a/releases/download/v0.59.1/po4a-v0.59.1.tar.gz : a906fd82a6cc3a8898c1fe55d14076f3376fa6879ce9b1828b8b125e2dbe495b
license    : GPL-2.0-or-later
component  : programming.devel
summary    : po4anything
description: |
    Maintain the translations of your documentation with ease (PO for anything)
patterns   :
    - /usr/share/man
builddeps  :
    - docbook-xml
    - perl-module-build
    - perl-pod-parser
rundeps    :
    - perl-gettext
environment: |
    export PERL_USE_UNSAFE_INC=1
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
